
üßπ **Limpeza dos Dados**
---

O conjunto de dados trabalhado no projeto √© referente ao gasto dos senadores aonde podemos identificar as colunas: da data do gasto , o tipo de gasto entre outras informa√ß√µes.

Estes conjuntos podem ser encontrados na p√°gina do CEAPS:
https://www12.senado.leg.br/transparencia/dados-abertos-transparencia/dados-abertos-ceaps?utm_source=ActiveCampaign&utm_medium=email&utm_content=%237DaysOfCode+-+Ci√™ncia+de+Dados+1%2F7%3A+Data+Cleaning+and+Preparation&utm_campaign=%5BAlura+%237Days+Of+Code%5D%28Java%29+Dia+1%2F7%3A+Consumir+uma+API+de+filmes

In [2]:
#importando a biblioteca utilizada para limpeza de dados
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
#importando os dados de 2022
data_2022 = pd.read_csv('despesa_ceaps_2022.csv', encoding= "cp1252", sep= ';')
data_2022.head()

,ANO,MES,SENADOR,TIPO_DESPESA,CNPJ_CPF,FORNECEDOR,DOCUMENTO,DATA,DETALHAMENTO,VALOR_REEMBOLSADO,COD_DOCUMENTO
0,2022,1,ACIR GURGACZ,"Aluguel de im√≥veis para escrit√≥rio pol√≠tico, c...",004.948.028-63,GILBERTO PISELO DO NASCIMENTO,001/22,03/01/2022,Despesa com pagamento de aluguel de im√≥vel par...,6000,2173614
1,2022,1,ACIR GURGACZ,Divulga√ß√£o da atividade parlamentar,26.320.603/0001-64,INFORMANAHORA,000000000000310/A,04/01/2022,Despesa com divulga√ß√£o da atividade parlamenta...,1500,2173615
2,2022,1,ACIR GURGACZ,Divulga√ß√£o da atividade parlamentar,13.659.201/0001-47,LINHA PURPURA FOTO E VIDEO LTDA,107,14/01/2022,Despesa com produ√ß√£o de texto e edi√ß√£o de v√≠de...,6000,2173616
3,2022,1,ACIR GURGACZ,Divulga√ß√£o da atividade parlamentar,23.652.846/0001-01,ROBERTO GUTIERREZ DA ROCHA M.E.I.,187,18/01/2022,Divulga√ß√£o da atividade parlamentar,1000,2173618
4,2022,1,ACIR GURGACZ,Divulga√ß√£o da atividade parlamentar,08.941.827/0001-01,RONDONIA DIN√ÇMICA COM. E SERV. DE INFORM√ÅTICA ...,000000000001772/A,17/01/2022,Divulga√ß√£o da atividade parlamentar,2000,2173617

In [4]:
#importando os dados de 2021
data_2021= pd.read_csv('despesa_ceaps_2021.csv', encoding= "cp1252", sep= ';')
data_2021.head(3)

,ANO,MES,SENADOR,TIPO_DESPESA,CNPJ_CPF,FORNECEDOR,DOCUMENTO,DATA,DETALHAMENTO,VALOR_REEMBOLSADO,COD_DOCUMENTO
0,2021,1,ACIR GURGACZ,"Aluguel de im√≥veis para escrit√≥rio pol√≠tico, c...",05.914.650/0001-66,ENERGISA,23.489.627,21/01/2021,Pagamento de energia el√©trica para uso do escr...,"75,29",2158003
1,2021,1,ACIR GURGACZ,"Aluguel de im√≥veis para escrit√≥rio pol√≠tico, c...",062.135.728-64,FERNANDO WALDEIR PACINI e ANA LUCIA DA SILVA S...,jan/21,05/01/2021,Despesa com pagamento de aluguel de im√≥vel par...,1000,2157367
2,2021,1,ACIR GURGACZ,"Aluguel de im√≥veis para escrit√≥rio pol√≠tico, c...",004.948.028-63,GILBERTO PISELO DO NASCIMENTO,001/21,06/01/2021,Despesa com aluguel de im√≥vel para uso do escr...,6000,2156383

In [5]:
#importando os dados de 2020
data_2020= pd.read_csv('despesa_ceaps_2020.csv', encoding= "cp1252", sep= ';')
data_2020.head(3)

,ANO,MES,SENADOR,TIPO_DESPESA,CNPJ_CPF,FORNECEDOR,DOCUMENTO,DATA,DETALHAMENTO,VALOR_REEMBOLSADO,COD_DOCUMENTO
0,2020,1,ACIR GURGACZ,"Aluguel de im√≥veis para escrit√≥rio pol√≠tico, c...",05.914.650/0001-66,ENERGISA,14764742,06/01/2020,Despesa com energia el√©trica para uso do escri...,"122,62",2141820
1,2020,1,ACIR GURGACZ,"Aluguel de im√≥veis para escrit√≥rio pol√≠tico, c...",05.914.650/0001-66,ENERGISA,14764741,06/01/2020,Despesa com energia el√©trica para uso do escri...,"137,75",2141818
2,2020,1,ACIR GURGACZ,"Aluguel de im√≥veis para escrit√≥rio pol√≠tico, c...",062.135.728-64,FERNANDO WALDEIR PACINI e ANA LUCIA DA SILVA S...,001/2020,06/01/2020,Despesa com pagamento de aluguel de im√≥vel par...,1000,2139025

In [6]:
#importando os dados de 2019
data_2019= pd.read_csv('despesa_ceaps_2019.csv', encoding= "cp1252", sep= ';')
data_2019.head(3)

,ANO,MES,SENADOR,TIPO_DESPESA,CNPJ_CPF,FORNECEDOR,DOCUMENTO,DATA,DETALHAMENTO,VALOR_REEMBOLSADO,COD_DOCUMENTO
0,2019,1,ACIR GURGACZ,"Aluguel de im√≥veis para escrit√≥rio pol√≠tico, c...",05.914.650/0001-66,ENERGISA,6582758,04/01/2019,Despesa com pagamento de energia el√©trica do e...,"66,02",2116543
1,2019,1,ACIR GURGACZ,"Aluguel de im√≥veis para escrit√≥rio pol√≠tico, c...",05.914.650/0001-66,ENERGISA,6582755,04/01/2019,Despesa com pagamento de energia el√©trica do e...,"139,98",2116546
2,2019,1,ACIR GURGACZ,"Aluguel de im√≥veis para escrit√≥rio pol√≠tico, c...",004.948.028-63,GILBERTO PISELO DO NASCIMENTO,119,07/01/2019,Despesa com pagamento de aluguel de im√≥vel par...,6000,2113817

Utilizando a fun√ß√£o concat para  unir os quatro datasets em apenas um para facilitar mais a an√°lise

In [7]:
#concatenando os dados de 2019,2020, 2021 e 2022 em um dataset 
data_concatenado= pd.concat([data_2022, data_2021, data_2020, data_2019], axis=0)
data_concatenado

,ANO,MES,SENADOR,TIPO_DESPESA,CNPJ_CPF,FORNECEDOR,DOCUMENTO,DATA,DETALHAMENTO,VALOR_REEMBOLSADO,COD_DOCUMENTO
0,2022,1,ACIR GURGACZ,"Aluguel de im√≥veis para escrit√≥rio pol√≠tico, c...",004.948.028-63,GILBERTO PISELO DO NASCIMENTO,001/22,03/01/2022,Despesa com pagamento de aluguel de im√≥vel par...,6000,2173614
1,2022,1,ACIR GURGACZ,Divulga√ß√£o da atividade parlamentar,26.320.603/0001-64,INFORMANAHORA,000000000000310/A,04/01/2022,Despesa com divulga√ß√£o da atividade parlamenta...,1500,2173615
2,2022,1,ACIR GURGACZ,Divulga√ß√£o da atividade parlamentar,13.659.201/0001-47,LINHA PURPURA FOTO E VIDEO LTDA,107,14/01/2022,Despesa com produ√ß√£o de texto e edi√ß√£o de v√≠de...,6000,2173616
3,2022,1,ACIR GURGACZ,Divulga√ß√£o da atividade parlamentar,23.652.846/0001-01,ROBERTO GUTIERREZ DA ROCHA M.E.I.,187,18/01/2022,Divulga√ß√£o da atividade parlamentar,1000,2173618
4,2022,1,ACIR GURGACZ,Divulga√ß√£o da atividade parlamentar,08.941.827/0001-01,RONDONIA DIN√ÇMICA COM. E SERV. DE INFORM√ÅTICA ...,000000000001772/A,17/01/2022,Divulga√ß√£o da atividade parlamentar,2000,2173617
...,...,...,...,...,...,...,...,...,...,...,...
21629,2019,1,ZEZ√â PERRELLA,"Passagens a√©reas, aqu√°ticas e terrestres nacio...",09.296.295/0001-60,Azul,O954UL,19/01/2019,"Companhia A√©rea: AZUL, Localizador: O954UL. Pa...","769,29",2113825
21630,2019,1,ZEZ√â PERRELLA,"Passagens a√©reas, aqu√°ticas e terrestres nacio...",09.296.295/0001-60,Azul,G9Z36V,24/01/2019,"Companhia A√©rea: AZUL, Localizador: G9Z36V. Pa...","310,62",2113828
21631,2019,1,ZEZ√â PERRELLA,"Passagens a√©reas, aqu√°ticas e terrestres nacio...",07.575.651/0001-59,GOL,WNQI4A,29/01/2019,"Companhia A√©rea: GOL, Localizador: WNQI4A. Pas...","1168,1",2114101
21632,2019,1,ZEZ√â PERRELLA,"Passagens a√©reas, aqu√°ticas e terrestres nacio...",33.937.681/0001-78,LATAM,NCCPIM,23/01/2019,"Companhia A√©rea: LATAM, Localizador: NCCPIM. P...","772,05",2113826
21633,2019,1,ZEZ√â PERRELLA,"Passagens a√©reas, aqu√°ticas e terrestres nacio...",33.937.681/0001-78,LATAM,MEYLWB,26/01/2019,"Companhia A√©rea: LATAM, Localizador: MEYLWB. P...","1755,17",2113830

Podemos percorrer o dataset e observar os valores √∫nicos que ocorrem em cada coluna

In [8]:
for var in data_concatenado:
  print('Coluna', var, 'Tipo da coluna', data_concatenado[var].dtype)
  print('Valores √∫nicos', data_concatenado[var].unique(), '\n')

Coluna ANO Tipo da coluna int64
Valores √∫nicos [2022 2021 2020 2019]

Coluna MES Tipo da coluna int64
Valores √∫nicos [ 1  2  3  4  5  6  7  8  9 10 11 12]

Coluna SENADOR Tipo da coluna object
Valores √∫nicos ['ACIR GURGACZ' 'ALESSANDRO VIEIRA' 'ALEXANDRE SILVEIRA' 'ALVARO DIAS'
 'ANGELO CORONEL' 'ANTONIO ANASTASIA' 'CARLOS F√ÅVARO' 'CARLOS PORTINHO'
 'CARLOS VIANA' 'CHICO RODRIGUES' 'CHIQUINHO FEITOSA' 'CID GOMES'
 'CONF√öCIO MOURA' 'DANIELLA RIBEIRO' 'D√ÅRIO BERGER' 'DAVI ALCOLUMBRE'
 'DRA. EUD√ìCIA' 'EDUARDO BRAGA' 'EDUARDO GIR√ÉO' 'EDUARDO GOMES'
 'EDUARDO VELLOSO' 'ELIANE NOGUEIRA' 'ELIZIANE GAMA' 'ELMANO F√âRRER'
 'ESPERIDI√ÉO AMIN' 'FABIANO CONTARATO' 'FABIO GARCIA'
 'FERNANDO BEZERRA COELHO' 'FERNANDO COLLOR' 'FERNANDO DUEIRE'
 'FL√ÅVIO ARNS' 'FL√ÅVIO BOLSONARO' 'GIORDANO' 'GUARACY SILVEIRA'
 'HUMBERTO COSTA' 'IRAJ√Å' 'IVETE DA SILVEIRA' 'IZALCI LUCAS'
 'JADER BARBALHO' 'JAQUES WAGNER' 'JARBAS VASCONCELOS' 'JAYME CAMPOS'
 'JEAN PAUL PRATES' 'JORGINHO MELLO' 'JOS√â AN√çBAL' 'JOS√â SERRA'
 'JULIO VENTURA' 'K√ÅTIA ABREU' 'LASIER MARTINS' 'LEILA BARROS'
 'LUCAS BARRETO' 'LUIS CARLOS HEINZE' 'LUIZ CARLOS DO CARMO'
 'LUIZ PASTORE' 'MAILZA GOMES' 'MARA GABRILLI' 'MARCELO CASTRO'
 'MARCIO BITTAR' 'MARCOS DO VAL' 'MARCOS ROG√âRIO' 'MARGARETH BUZETTI'
 'MARIA DAS VIT√ìRIAS' 'MARIA DO CARMO ALVES'
 'MARIA ELIZA DE AGUIAR E SILVA' 'MECIAS DE JESUS' 'NELSINHO TRAD'
 'NILDA GONDIM' 'OGARI PACHECO' 'OMAR AZIZ' 'ORIOVISTO GUIMAR√ÉES'
 'OTTO ALENCAR' 'PAULO PAIM' 'PAULO ROCHA' 'PL√çNIO VAL√âRIO'
 'RAFAEL TEN√ìRIO' 'RANDOLFE RODRIGUES' 'RENAN CALHEIROS' 'ROBERTH BRINGEL'
 'ROBERTO ROCHA' 'RODRIGO CUNHA' 'RODRIGO PACHECO' 'ROG√âRIO CARVALHO'
 'ROM√ÅRIO' 'ROSE DE FREITAS' 'SAMUEL ARAUJO' 'S√âRGIO PETEC√ÉO'
 'SIMONE TEBET' 'SORAYA THRONICKE' 'STYVENSON VALENTIM' 'TASSO JEREISSATI'
 'TELM√ÅRIO MOTA' 'VANDERLAN CARDOSO' 'VENEZIANO VITAL DO R√äGO'
 'WELLINGTON FAGUNDES' 'WEVERTON ROCHA' 'ZENAIDE MAIA' 'ZEQUINHA MARINHO'
 'CIRO NOGUEIRA' 'MAJOR OLIMPIO' 'NAILDE PANTA' 'NEY SUASSUNA'
 'VIRGINIO DE CARVALHO' 'AROLDE DE OLIVEIRA' 'DIEGO TAVARES'
 'JOS√â MARANH√ÉO' 'JU√çZA SELMA' 'PAULO ALBUQUERQUE' 'PRISCO BEZERRA'
 'A√âCIO NEVES' 'ALOYSIO NUNES FERREIRA' 'ANA AM√âLIA' '√ÇNGELA PORTELA'
 'ANT√îNIO CARLOS VALADARES' 'ARMANDO MONTEIRO' 'ATA√çDES OLIVEIRA'
 'BENEDITO DE LIRA' 'BLAIRO MAGGI' 'C√ÅSSIO CUNHA LIMA' 'DALIRIO BEBER'
 'EDISON LOB√ÉO' 'EDUARDO AMORIM' 'FLEXA RIBEIRO' 'GARIBALDI ALVES FILHO'
 'GLEISI HOFFMANN' 'H√âLIO JOS√â' 'IVO CASSOL' 'JO√ÉO ALBERTO SOUZA'
 'JO√ÉO CAPIBERIBE' 'JORGE VIANA' 'JOS√â AGRIPINO' 'JOS√â MEDEIROS'
 'JOS√â PIMENTEL' 'L√çDICE DA MATA' 'LINDBERGH FARIAS' 'L√öCIA V√ÇNIA'
 'MAGNO MALTA' 'MARTA SUPLICY' 'PAULO BAUER'
 'PEDRO CHAVES DOS SANTOS FILHO' 'RAIMUNDO LIRA' 'RENILDE BULH√ïES'
 'RICARDO FERRA√áO' 'ROBERTO REQUI√ÉO' 'ROMERO JUC√Å' 'SIQUEIRA CAMPOS'
 'VALDIR RAUPP' 'VANESSA GRAZZIOTIN' 'VICENTINHO ALVES' 'WALDEMIR MOKA'
 'WALTER PINHEIRO' 'WILDER MORAIS' 'Z√â SANTANA' 'ZEZ√â PERRELLA']

Coluna TIPO_DESPESA Tipo da coluna object
Valores √∫nicos ['Aluguel de im√≥veis para escrit√≥rio pol√≠tico, compreendendo despesas concernentes a eles.'
 'Divulga√ß√£o da atividade parlamentar'
 'Passagens a√©reas, aqu√°ticas e terrestres nacionais'
 'Contrata√ß√£o de consultorias, assessorias, pesquisas, trabalhos t√©cnicos e outros servi√ßos de apoio ao exerc√≠cio do mandato parlamentar'
 'Locomo√ß√£o, hospedagem, alimenta√ß√£o, combust√≠veis e lubrificantes'
 'Aquisi√ß√£o de material de consumo para uso no escrit√≥rio pol√≠tico, inclusive aquisi√ß√£o ou loca√ß√£o de software, despesas postais, aquisi√ß√£o de publica√ß√µes, loca√ß√£o de m√≥veis e de equipamentos. '
 'Servi√ßos de Seguran√ßa Privada']

Coluna CNPJ_CPF Tipo da coluna object
Valores √∫nicos ['004.948.028-63' '26.320.603/0001-64' '13.659.201/0001-47' ...
 '83.928.622/0001-01' '30.495.249/0001-86' '16.982.779/0001-28']

Coluna FORNECEDOR Tipo da coluna object
Valores √∫nicos ['GILBERTO PISELO DO NASCIMENTO' 'INFORMANAHORA'
 'LINHA PURPURA FOTO E VIDEO LTDA' ... 'Lokamig Rent a Car'
 'Posto Vila da Serra Ltda' 'Azul']

Coluna DOCUMENTO Tipo da coluna object
Valores √∫nicos ['001/22' '000000000000310/A' '107' ... 'WNQI4A' 'NCCPIM' 'MEYLWB']

Coluna DATA Tipo da coluna object
Valores √∫nicos ['03/01/2022' '04/01/2022' '14/01/2022' ... '26/10/2018' '07/10/2010'
 '14/10/2010']

Coluna DETALHAMENTO Tipo da coluna object
Valores √∫nicos ['Despesa com pagamento de aluguel de im√≥vel para uso do escrit√≥rio pol√≠tico do Senador Acir Gurgacz em Ji-Paran√°/RO.'
 'Despesa com divulga√ß√£o da atividade parlamentar no website www.informanahora.com'
 'Despesa com produ√ß√£o de texto e edi√ß√£o de v√≠deo para divulga√ß√£o da atividade parlamentar'
 ...
 'Companhia A√©rea: GOL, Localizador: WNQI4A. Passageiros: GUITHYERRI SOUSA DE ALMEIDA (Matr√≠cula 260979, COMISSIONADO), Voo: 1703 - CNF/BSB - 29/01/2019; BR√ÅULIO CAMPOS PIMENTA (Matr√≠cula 237192, COMISSIONADO), Voo: 1703 - CNF/BSB - 29/01/2019;'
 'Companhia A√©rea: LATAM, Localizador: NCCPIM. Passageiros: JOS√â PERRELLA DE OLIVEIRA COSTA (Matr√≠cula 247586, PARLAMENTAR), Voo: 3759 - CNF/SDU - 24/01/2019;'
 'Companhia A√©rea: LATAM, Localizador: MEYLWB. Passageiros: JOS√â PERRELLA DE OLIVEIRA COSTA (Matr√≠cula 247586, PARLAMENTAR), Voo: 3026 - SDU/BSB - 29/01/2019;']

Coluna VALOR_REEMBOLSADO Tipo da coluna object
Valores √∫nicos ['6000' '1500' '1000' ... '1168,1' '772,05' '1755,17']

Coluna COD_DOCUMENTO Tipo da coluna int64
Valores √∫nicos [2173614 2173615 2173616 ... 2114101 2113826 2113830]

Vamos verificar se existem colunas duplicadas

In [9]:
data_concatenado.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
21629    False
21630    False
21631    False
21632    False
21633    False
Length: 69246, dtype: bool

As colunas: 'C√ìD_DOCUMENTO', 'DOCUMENTO' e 'DETALHAMENTO' s√£o irrelevantes na an√°lise que ser√° feita por isso elas ser√£o deletadas com o m√©todo drop. Por padr√£o o m√©todo drop apaga as linhas no nosso caso ser√£o apagadas as colunas para isso basta especificar axis =*1*

In [10]:
data_concatenado = data_concatenado.drop(['COD_DOCUMENTO', 'DOCUMENTO', 'DETALHAMENTO'], axis =1)
data_concatenado.head(3)

,ANO,MES,SENADOR,TIPO_DESPESA,CNPJ_CPF,FORNECEDOR,DATA,VALOR_REEMBOLSADO
0,2022,1,ACIR GURGACZ,"Aluguel de im√≥veis para escrit√≥rio pol√≠tico, c...",004.948.028-63,GILBERTO PISELO DO NASCIMENTO,03/01/2022,6000
1,2022,1,ACIR GURGACZ,Divulga√ß√£o da atividade parlamentar,26.320.603/0001-64,INFORMANAHORA,04/01/2022,1500
2,2022,1,ACIR GURGACZ,Divulga√ß√£o da atividade parlamentar,13.659.201/0001-47,LINHA PURPURA FOTO E VIDEO LTDA,14/01/2022,6000

In [11]:
data_concatenado

,ANO,MES,SENADOR,TIPO_DESPESA,CNPJ_CPF,FORNECEDOR,DATA,VALOR_REEMBOLSADO
0,2022,1,ACIR GURGACZ,"Aluguel de im√≥veis para escrit√≥rio pol√≠tico, c...",004.948.028-63,GILBERTO PISELO DO NASCIMENTO,03/01/2022,6000
1,2022,1,ACIR GURGACZ,Divulga√ß√£o da atividade parlamentar,26.320.603/0001-64,INFORMANAHORA,04/01/2022,1500
2,2022,1,ACIR GURGACZ,Divulga√ß√£o da atividade parlamentar,13.659.201/0001-47,LINHA PURPURA FOTO E VIDEO LTDA,14/01/2022,6000
3,2022,1,ACIR GURGACZ,Divulga√ß√£o da atividade parlamentar,23.652.846/0001-01,ROBERTO GUTIERREZ DA ROCHA M.E.I.,18/01/2022,1000
4,2022,1,ACIR GURGACZ,Divulga√ß√£o da atividade parlamentar,08.941.827/0001-01,RONDONIA DIN√ÇMICA COM. E SERV. DE INFORM√ÅTICA ...,17/01/2022,2000
...,...,...,...,...,...,...,...,...
21629,2019,1,ZEZ√â PERRELLA,"Passagens a√©reas, aqu√°ticas e terrestres nacio...",09.296.295/0001-60,Azul,19/01/2019,"769,29"
21630,2019,1,ZEZ√â PERRELLA,"Passagens a√©reas, aqu√°ticas e terrestres nacio...",09.296.295/0001-60,Azul,24/01/2019,"310,62"
21631,2019,1,ZEZ√â PERRELLA,"Passagens a√©reas, aqu√°ticas e terrestres nacio...",07.575.651/0001-59,GOL,29/01/2019,"1168,1"
21632,2019,1,ZEZ√â PERRELLA,"Passagens a√©reas, aqu√°ticas e terrestres nacio...",33.937.681/0001-78,LATAM,23/01/2019,"772,05"
21633,2019,1,ZEZ√â PERRELLA,"Passagens a√©reas, aqu√°ticas e terrestres nacio...",33.937.681/0001-78,LATAM,26/01/2019,"1755,17"

Verificando se existem dados do tipo Not a Number(NaN)

In [12]:
data_concatenado.isna().sum()

ANO                  0
MES                  0
SENADOR              0
TIPO_DESPESA         0
CNPJ_CPF             0
FORNECEDOR           0
DATA                 0
VALOR_REEMBOLSADO    0
dtype: int64

In [13]:
data_concatenado.isnull().sum()

ANO                  0
MES                  0
SENADOR              0
TIPO_DESPESA         0
CNPJ_CPF             0
FORNECEDOR           0
DATA                 0
VALOR_REEMBOLSADO    0
dtype: int64

Verificando os tipos de vari√°veis que foi poss√≠vel identificar

In [14]:
#tipos de vari√°veis de cada coluna
data_concatenado.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 69246 entries, 0 to 21633
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ANO                69246 non-null  int64
 1   MES                69246 non-null  int64
 2   SENADOR            69246 non-null  object
 3   TIPO_DESPESA       69246 non-null  object
 4   CNPJ_CPF           69246 non-null  object
 5   FORNECEDOR         69246 non-null  object
 6   DATA               69246 non-null  object
 7   VALOR_REEMBOLSADO  69246 non-null  object
dtypes: int64(2), object(6)
memory usage: 4.8+ MB

Podemos perceber que algumas  vari√°veis est√£o sendo lidas de maneira incorreta para isso vamos utilizar o m√©todo astype para atribuir os valores corretos as colunas

In [15]:
#Senador, tipo de despesa, fornecedor s√£o strings
data_concatenado["SENADOR"] = data_concatenado["SENADOR"].astype('string')
data_concatenado['TIPO_DESPESA']= data_concatenado['TIPO_DESPESA'].astype('string')
data_concatenado['FORNECEDOR']= data_concatenado['FORNECEDOR'].astype('string')

#Valor reembolsado √© do tipo float para isso precisamos transforma as v√≠rgulas em pontos e permanecer os pontos em pontos
#Na coluna reembolso precisamos utilizar uma fun√ß√£o para assim transformar a coluna no tipo certo que seria float
data_concatenado['VALOR_REEMBOLSADO'] = data_concatenado['VALOR_REEMBOLSADO'] .apply(lambda x: float(x.replace(".","").replace(",",".")))

In [16]:
data_concatenado.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 69246 entries, 0 to 21633
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ANO                69246 non-null  int64
 1   MES                69246 non-null  int64
 2   SENADOR            69246 non-null  string
 3   TIPO_DESPESA       69246 non-null  string
 4   CNPJ_CPF           69246 non-null  object
 5   FORNECEDOR         69246 non-null  string
 6   DATA               69246 non-null  object
 7   VALOR_REEMBOLSADO  69246 non-null  float64
dtypes: float64(1), int64(2), object(2), string(3)
memory usage: 4.8+ MB

#**Exportando os  Dados**

Nesta etapa exportaremos as modifica√ß√µes feitas no dataset para este ser utilizado na segunda etapa do projeto

In [18]:
data_concatenado = data_concatenado.to_csv('data_concatenado.csv', sep=';')

AttributeError: ignored